import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

    mainSidebar: [
        {
            type: "category",
            label: "Game Packages",
            items: [
                {
                    type: "category",
                    label: "Unity",
                    link: {
                        type: "doc",
                        id: "Game Packages/Unity/intro",
                    },
                    items: [
                        {
                            type: "autogenerated",
                            dirName: "Game Packages/Unity/Packages",
                        },
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "About",
            items: [{ type: "autogenerated", dirName: "About" }],
        },
        {
            type: "link",
            label: "GitHub",
            href: "https://github.com/juanpablomaggi",
        },
    ],

    gamePackagesSidebar: [
        {
            type: "category",
            label: "Unity",
            link: {
                type: "doc",
                id: "Game Packages/Unity/intro",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "Game Packages/Unity/Packages",
                },
            ],
        },
    ],
};

export default sidebars;
