import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    mainSidebar: [
        {
            type: "category",
            label: "Game Packages",
            items: [
                {
                    type: "category",
                    label: "Unity",
                    link: {
                        type: "doc",
                        id: "Game Packages/Unity/intro",
                    },
                    items: [
                        {
                            type: "autogenerated",
                            dirName: "Game Packages/Unity/Packages",
                        },
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "About",
            items: [{ type: "autogenerated", dirName: "About" }],
        },
        {
            type: "link",
            label: "GitHub",
            href: "https://github.com/juanpablomaggi",
        },
    ],

    gamePackagesSidebar: [
        {
            type: "category",
            label: "Unity",
            link: {
                type: "doc",
                id: "Game Packages/Unity/intro",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "Game Packages/Unity/Packages",
                },
            ],
        }
    ],
};

export default sidebars;
